openai_api_key: "" # Please enter your openai api key
input_path: "./input_csv_files" # Please enter your csv file input path
temperature: 0.0 # Temperature of the LLM 
model_name: "gpt-4o-mini"
output_path: "./output" # Please enter your json file out path
thread_num: 1 # Please specify how many workers to perform the extraction task
max_retry: 3 # Please specify maximum iteration during extraction 